num_of_workers: 1
queue_size: 100
queue_no_refill_limit: 20
pg_access:
  host: localhost
  dbname: twitter
  user: ""
  password: ""
cookies:
  _twitter_sess: ""
  ct0: ""

  auth_token: ""
  guest_id: ""
  kdt: ""
  personalization_id: ""
  twid: ""
  dnt: 1

  _ga: ""
  csrf_same_site: 1
  csrf_same_site_set: 1
  rweb_optin: side_no_out
  ads_prefs: ""
headers:
  authorization: ""
  connection: "keep-alive"