version: '3'

services:
  neo4j:
    image: neo4j:3.5
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    environment:
      NEO4J_AUTH: neo4j/12345
    volumes:
      - ./neo4j-data/conf:/conf:Z
      - ./neo4j-data/data:/data:Z
      - ./neo4j-data/logs:/logs:Z
      - ./neo4j-data/plugins:/plugins:Z

  spark:
    build: ./spark
    environment:
      - SPARK_CLASSPATH=/home/jovyan/drivers/postgresql-42.2.10.jar,/home/jovyan/drivers/graphframes-0.7.0-spark2.4-s_2.11.jar
      - SPARK_OPTS="--packages graphframes:graphframes-0.7.0-spark2.4-s_2.11.jar"
    ports:
      - '8888:8888'
    volumes:
      - ./spark/data:/home/jovyan/data:Z
      - ./spark/drivers:/home/jovyan/drivers
      - ./spark/notebooks:/home/jovyan/work:Z
    entrypoint: "start.sh jupyter lab --LabApp.token=''"

#  postgres:
#    image: postgres:11
#    ports:
#      - '5432:5432'
#    volumes:
#      - '/Users/konstantin/Library/Application Support/Postgres/var-11:/var/lib/postgresql/data:Z'

